config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'    }
  root 'welcome#index'
  # root to: 'video#index'
  get 'welcome/demo'
  get 'welcome/index'
  post 'welcome/subscriber_request'
  
  resources :videos, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :subscriber
end

app/models/video.rb
class Video < ApplicationRecord
  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i

    validates :link, presence: true, format: YT_LINK_FORMAT

end

app/models/wel_come.rb
class WelCome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  def index
    @videos = Video.order('created_at DESC')
  end

  def new
    @video = Video.new
  end
  
  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def video_params
    params.require(:video).permit(:link)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @all = YoutubeSearch.search('cats', :page => 10, :per_page => 4).first
    @videos = Video.order('created_at DESC')
  end
  
  def demo
  end
  
  def subscriber_request
   @email = connect_params[:email]
   UserMailer.subscriber(@email).deliver_now
   if !Subscriber.exists?(email: @email)
     Subscriber.create(email: @email, user_id: current_user.id)
   end
   redirect_to root_path
  end
  
  private

  def connect_params
    params.permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/globals/_footer.html.erb
  <!-- ***** Footer Area Start ***** -->
  <footer class="footer-area section-padding-80-0">
    <div class="container">
      <div class="row">

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-footer-widget mb-80">
            <!-- Widget Title -->
            <h4 class="widget-title">About Us</h4>

            <p>It is a long established fact that a reader will be distracted by the readable content.</p>
            <div class="copywrite-content">
              <p>&copy;

<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-footer-widget mb-80">
            <!-- Widget Title -->
            <h4 class="widget-title">Categories</h4>

            <!-- Catagories Nav -->
            <nav>
              <ul class="catagories-nav">
                <li><a href="#">Entrepreneurship</a></li>
                <li><a href="#">Media</a></li>
                <li><a href="#">Tech</a></li>
                <li><a href="#">Tutorials</a></li>
              </ul>
            </nav>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-footer-widget mb-80">
            <!-- Widget Title -->
            <h4 class="widget-title">Lastest Episodes</h4>

            <!-- Single Latest Episodes -->
            <div class="single-latest-episodes">
              <p class="episodes-date">December 9, 2018</p>
              <a href="#" class="episodes-title">Episode 205 - See Ya In Three!</a>
            </div>
            <!-- Single Latest Episodes -->
            <div class="single-latest-episodes">
              <p class="episodes-date">December 8, 2018</p>
              <a href="#" class="episodes-title">Episode 204 - See Ya In Two!</a>
            </div>
          </div>
        </div>

        <!-- Single Footer Widget -->
        <div class="col-12 col-sm-6 col-lg-3">
          <div class="single-footer-widget mb-80">
            <!-- Widget Title -->
            <h4 class="widget-title">Follow Us</h4>
            <!-- Social Info -->
            <div class="footer-social-info">
              <a href="#" class="facebook" data-toggle="tooltip" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="twitter" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="pinterest" data-toggle="tooltip" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a>
              <a href="#" class="instagram" data-toggle="tooltip" data-placement="top" title="Instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="youtube" data-toggle="tooltip" data-placement="top" title="YouTube"><i class="fa fa-youtube-play"></i></a>
            </div>
            <!-- App Download Button -->
            <div class="app-download-button mt-30">
              <a href="#">
                <%= image_tag "app-store.png", alt: '' %>
              </a>
              <a href="#">
                <%= image_tag "google-play.png", alt: '' %>
              </a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </footer>

app/views/globals/_navbar.html.erb
  <header class="header-area">
    <div class="main-header-area">
      <div class="classy-nav-container breakpoint-off">
        <nav class="classy-navbar justify-content-between" id="pocaNav">
          <canvas id="canvas"></canvas>
          <div class="classy-navbar-toggler">
            <span class="navbarToggler"><span></span><span></span><span></span></span>
          </div>
          <div class="classy-menu">

            <div class="classycloseIcon">
              <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
            </div>

            <div class="classynav">
              <ul id="nav">
                <li class="current-item">
                <%= link_to "Home" , welcome_demo_path %>
                </li>
                <li><a href="#">Pages</a>
                  <ul class="dropdown">
                    <li><a href="./index.html">- Home</a></li>
                    <li><a href="./podcast.html">- Podcast</a></li>
                    <li><a href="./single-podcast.html">- Single Podcast</a></li>
                    <li><a href="./about.html">- About Us</a></li>
                    <li><a href="./blog.html">- Blog</a></li>
                    <li><a href="./single-blog.html">- Blog Details</a></li>
                    <li><a href="./contact.html">- Contact</a></li>
                    <li><a href="#">- Dropdown</a>
                      <ul class="dropdown">
                        <li><a href="#">- Dropdown Item</a></li>
                        <li><a href="#">- Dropdown Item</a>
                          <ul class="dropdown">
                            <li><a href="#">- Even Dropdown</a></li>
                            <li><a href="#">- Even Dropdown</a></li>
                            <li><a href="#">- Even Dropdown</a></li>
                            <li><a href="#">- Even Dropdown</a></li>
                          </ul>
                        </li>
                        <li><a href="#">- Dropdown Item</a></li>
                        <li><a href="#">- Dropdown Item</a></li>
                      </ul>
                    </li>
                  </ul>
                </li>
                <li><a href="./about.html">About</a></li>
                <li><a href="#">Blog</a>
                  <ul class="dropdown">
                    <li><a href="./blog.html">- Blog</a></li>
                    <li><a href="./single-blog.html">- Blog Details</a></li>
                  </ul>
                </li>
                <li><a href="./contact.html">Contact</a></li>
              </ul>

              <div class="top-search-area">
                <form action="index.html" method="post">
                  <input type="search" name="top-search-bar" class="form-control" placeholder="Search and hit enter...">
                  <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                </form>
              </div>

              <div class="top-social-area">
                <a href="#" class="fa fa-facebook" aria-hidden="true"></a>
                <a href="#" class="fa fa-instagram" aria-hidden="true"></a>
                <a href="#" class="fa fa-youtube-play" aria-hidden="true"></a>
              </div>

            </div>
          </div>
          
          <div class="w3-container">
            <ul class=" one-line">
              <li class="nav navbar-right">
                <div class="w3-dropdown-click pull-right">
                  <strong><p onclick= "myFunction()" class="text_height user_email" ><%= current_user.email%></p></strong>
                  <div id="Demo" class="w3-dropdown-content w3-bar-block w3-card-4 w3-animate-zoom">
                    <% if user_signed_in? %>
                      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'w3-bar-item w3-button' %>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'w3-bar-item w3-button' %>
                    <% else %>
                      <%= link_to "Sign up", new_user_registration_path, :class => 'w3-bar-item w3-button' %>
                      <%= link_to "Login", new_user_session_path, :class => 'w3-bar-item w3-button' %>
                    <% end %>
                  </div>
              </li>
            </ul>
          </div>
    
        </nav>
      </div>
    </div>
  </header>

app/views/globals/_sidebar.html.erb
<div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none" id="mySidebar">
  <button class="w3-bar-item w3-button w3-large" onclick="w3_close()">Close &times;</button>
    <%= link_to 'New Invoice',  class: "w3-bar-item w3-button w3-hover-blue" %>
    <%= link_to 'Invoices List', class: "w3-bar-item w3-button w3-hover-blue" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Dj Sonu</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-visit-control" content="reload">
    <meta name="turbolinks-cache-control" content="no-cache">

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"> -->
    <!-- <script src="http://code.jquery.com/jquery-1.9.1.js"></script> -->
    <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->

  <meta name="description" content="Poca - Podcast &amp; Audio Template">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Favicon -->
  <link rel="icon" href="./img/core-img/favicon.ico">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if current_user.present? %>
      <%= render 'globals/navbar' %>
      <%#= render 'globals/sidebar' %>

      <div id="main">
        <div class="w3-container">
          <div class="">
            <% flash.each do |key, value| %>
            <% if value != nil %>
            <div class="alert alert-success">
              <%= value %>
            </div>
            <% end %>
            <% end %>
          </div>
          <% end %>
          <%= yield %>
        </div>
      </div>
    <%= render 'globals/footer' %>
  </body>
</html>

app/views/video/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Share your videos with the world!</h1>
    <p>Click the button below to share your video from YouTube.</p>
    <p>
      <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
</div>

app/views/video/new.html.erb
<div class="container">
  <h1>New video</h1>

  <%= form_for @video do |f| %>
    <%= render 'shared/errors', object: @video %>

    <div class="form-group">
      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control', required: true %>
      <span class="help-block">A link to the video on YouTube.</span>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
  <div id="preloader">
    <div class="preloader-thumbnail">
      <%= image_tag "preloader.png", alt: '' %>
    </div>
    
    
    <div class="jumbotron">
      <div class="container">
        <h1>Share your videos with the world!</h1>
        <p>Click the button below to share your video from YouTube.</p>
        <p>
          <%= link_to 'Add video now!', new_video_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>

    <% if @videos.any? %>
      <div class="container">
        <h1>Latest videos</h1>
        <div id="player-wrapper"></div>
        <% @videos.in_groups_of(3) do |group| %>
          <div class="row">
            <% group.each do |video| %>
              <% if video %>
                <div class="col-md-4">
                  <div class="yt_video thumbnail">
                    <%= link_to image_tag("https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,
                                          class: 'img-rounded'),
                                "https://www.youtube.com/watch?v=#{video.uid}", target: '_blank' %>
                    <div class="caption">
                      <h5><%= video.title %></h5>
                      <p>Published at <%= video.published_at.strftime('%-d %B %Y %H:%M:%S') %></p>
                      <p>
                        <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> <%= video.likes %>
                        <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> <%= video.dislikes %>
                      </p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
  <section class="welcome-area">
    <div class="welcome-slides owl-carousel">
      <div class="welcome-welcome-slide bg-img bg-overlay" style="background-image: url(<%= asset_path '2.jpg' %>);">
        <div class="container h-100">
          <div class="row h-100 align-items-center">
          </div>
        </div>
    </div>
  </section>

  <section class="poca-latest-epiosodes section-padding-80">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>Latest Episodes</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="poca-projects-menu mb-30 wow fadeInUp" data-wow-delay="0.3s">
        <div class="text-center portfolio-menu">
          <button class="btn active" data-filter="*">All</button>
          <button class="btn" data-filter=".entre">Entrepreneurship</button>
          <button class="btn" data-filter=".media">Media</button>
          <button class="btn" data-filter=".tech">Tech</button>
          <button class="btn" data-filter=".tutor">Tutorials</button>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row poca-portfolio">
        <div class="col-12 col-md-6 single_gallery_item entre wow fadeInUp" data-wow-delay="0.2s">
          <div class="poca-music-area style-2 d-flex align-items-center flex-wrap">
            <div class="poca-music-thumbnail">
              <%= image_tag "5.jpg", alt: '' %>
            </div>
            <div class="poca-music-content text-center">
              <span class="music-published-date mb-2">December 9, 2018</span>
              <h2>Episode 201 - You Don’t Know Squat!</h2>
              <div class="music-meta-data">
                <p>By <a href="#" class="music-author">Admin</a> | <a href="#" class="music-catagory">Tutorials</a> | <a href="#" class="music-duration">00:02:56</a></p>
              </div>
              <div class="poca-music-player">
                <audio preload="auto" controls>
                    <%= asset_path('dummy-audio.mp3') %>
                </audio>
              </div>
              <div class="likes-share-download d-flex align-items-center justify-content-between">
                <a href="#"><i class="fa fa-heart" aria-hidden="true"></i> Like (29)</a>
                <div>
                  <a href="#" class="mr-4"><i class="fa fa-share-alt" aria-hidden="true"></i> Share(04)</a>
                  <a href="#"><i class="fa fa-download" aria-hidden="true"></i> Download (12)</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6 single_gallery_item entre tutor wow fadeInUp" data-wow-delay="0.2s">
          <div class="poca-music-area style-2 d-flex align-items-center flex-wrap">
            <div class="poca-music-thumbnail">
              <%= image_tag "6.jpg", alt: '' %>
            </div>
            <div class="poca-music-content text-center">
              <span class="music-published-date mb-2">December 9, 2018</span>
              <h2>Episode 202 - I Want A New Judge!</h2>
              <div class="music-meta-data">
                <p>By <a href="#" class="music-author">Admin</a> | <a href="#" class="music-catagory">Tutorials</a> | <a href="#" class="music-duration">00:02:56</a></p>
              </div>
              <div class="poca-music-player">
                <audio preload="auto" controls>
                  <%= asset_path('dummy-audio.mp3') %>
                </audio>
              </div>
              <div class="likes-share-download d-flex align-items-center justify-content-between">
                <a href="#"><i class="fa fa-heart" aria-hidden="true"></i> Like (29)</a>
                <div>
                  <a href="#" class="mr-4"><i class="fa fa-share-alt" aria-hidden="true"></i> Share(04)</a>
                  <a href="#"><i class="fa fa-download" aria-hidden="true"></i> Download (12)</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6 single_gallery_item media wow fadeInUp" data-wow-delay="0.2s">
          <div class="poca-music-area style-2 d-flex align-items-center flex-wrap">
            <div class="poca-music-thumbnail">
              <%= image_tag "8.jpg", alt: '' %>
            </div>
            <div class="poca-music-content text-center">
              <span class="music-published-date mb-2">December 9, 2018</span>
              <h2>Episode 204 - The Last Blockbuster</h2>
              <div class="music-meta-data">
                <p>By <a href="#" class="music-author">Admin</a> | <a href="#" class="music-catagory">Tutorials</a> | <a href="#" class="music-duration">00:02:56</a></p>
              </div>
              <div class="poca-music-player">
                <audio preload="auto" controls>
                  <%= asset_path('dummy-audio.mp3') %>
                </audio>
              </div>
              <div class="likes-share-download d-flex align-items-center justify-content-between">
                <a href="#"><i class="fa fa-heart" aria-hidden="true"></i> Like (29)</a>
                <div>
                  <a href="#" class="mr-4"><i class="fa fa-share-alt" aria-hidden="true"></i> Share(04)</a>
                  <a href="#"><i class="fa fa-download" aria-hidden="true"></i> Download (12)</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-12 col-md-6 single_gallery_item tech wow fadeInUp" data-wow-delay="0.2s">
          <div class="poca-music-area style-2 d-flex align-items-center flex-wrap">
            <div class="poca-music-thumbnail">
              <%= image_tag "10.jpg", alt: '' %>
            </div>
            <div class="poca-music-content text-center">
              <span class="music-published-date mb-2">December 9, 2018</span>
              <h2>Episode 206 - Let’s Get This Party Started!</h2>
              <div class="music-meta-data">
                <p>By <a href="#" class="music-author">Admin</a> | <a href="#" class="music-catagory">Tutorials</a> | <a href="#" class="music-duration">00:02:56</a></p>
              </div>
              <div class="poca-music-player">
                <audio preload="auto" controls>
                  <%= asset_path('dummy-audio.mp3') %>
                </audio>
              </div>
              <div class="likes-share-download d-flex align-items-center justify-content-between">
                <a href="#"><i class="fa fa-heart" aria-hidden="true"></i> Like (29)</a>
                <div>
                  <a href="#" class="mr-4"><i class="fa fa-share-alt" aria-hidden="true"></i> Share(04)</a>
                  <a href="#"><i class="fa fa-download" aria-hidden="true"></i> Download (12)</a>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <a href="#" class="btn poca-btn mt-70">Load More</a>
        </div>
      </div>
    </div>
  </section>

  <section class="featured-guests-area">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="section-heading text-center">
            <h2>Featured Guests</h2>
            <div class="line"></div>
          </div>
        </div>
      </div>

      <div class="row justify-content-around">
        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <div class="single-featured-guest mb-80">
            <%= image_tag "25.jpg", alt: '' %>
            <div class="guest-info">
              <h5>Alfred Day</h5>
              <span>PRODUCER</span>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <div class="single-featured-guest mb-80">
            <%= image_tag "26.jpg", alt: '' %>
            <div class="guest-info">
              <h5>Jayden White</h5>
              <span>DRUMMER</span>
            </div>
          </div>
        </div>

        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
          <div class="single-featured-guest mb-80">
            <%= image_tag "27.jpg", alt: '' %>
            <div class="guest-info">
              <h5>Vincent Reid</h5>
              <span>ENTREPRENEUR</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="poca-newsletter-area bg-img bg-overlay pt-50 jarallax" style="background-image: url(<%= asset_path '15.jpg' %>);">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-12 col-lg-6">
          <div class="newsletter-content mb-50">
            <h2>Sign Up To Newsletter</h2>
            <h6>Subscribe to receive info on our latest news and episodes</h6>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="newsletter-form mb-50">
              <%= form_tag 'welcome/subscriber_request', method: :post do %>
                <%= text_field_tag :email, params[:email], placeholder: 'Your Email', class: 'form-control', required: true %>
                <%= submit_tag "Subscribe", class: 'btn subscribe_button' %>
              <% end %>
          </div>
          
        </div>
      </div>
    </div>
  </section>